# Generated by Django 2.1.7 on 2019-02-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='服务器名字')),
                ('description', models.CharField(max_length=256, verbose_name='服务器描述')),
                ('directory', models.CharField(max_length=256, verbose_name='服务器目录')),
                ('status', models.CharField(default='unknown', max_length=32, verbose_name='服务器状态')),
                ('last_checked_at', models.DateTimeField()),
                ('last_started_at', models.DateTimeField()),
            ],
        ),
    ]
